all:
  vars:
    ansible_user: ec2-user
    ansible_become: true
    ansible_become_method: sudo
    ansible_ssh_common_args: "-o ProxyJump=ec2-user@{{ lookup('env','BASTION_IP') }}"

  children:
    bastion:
      hosts:
        bastion:
          ansible_host: "{{ lookup('env', 'BASTION_IP') }}"

    ceph:
      hosts:
        node1:
          ansible_host: "{{ lookup('env', 'NODE1_IP') }}"
        node2:
          ansible_host: "{{ lookup('env', 'NODE2_IP') }}"
        node3:
          ansible_host: "{{ lookup('env', 'NODE3_IP') }}"
